import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

// Import your global components
import Sidebar from "./components/sidebar";
import Footer from "./components/footer";

// Fonts
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// Metadata
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

// Layout component
export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div className="flex min-h-screen">
          {/* Sidebar */}
          <Sidebar />

          {/* Main Content & Footer */}
          <div className="flex flex-col flex-1">
            <main className="flex-1 p-6 bg-gray-100">{children}</main>
            <Footer />
          </div>
        </div>
      </body>
    </html>
  );
}
